"""empty message

Revision ID: 401b83f7d71b
Revises: 81b5f1651ab8
Create Date: 2023-12-13 13:18:57.913341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401b83f7d71b'
down_revision = '81b5f1651ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('title_html', sa.String(length=250), nullable=True))
        batch_op.alter_column('body_html',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=2500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body_html',
               existing_type=sa.String(length=2500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.drop_column('title_html')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
