"""Add new field to Post table

Revision ID: 50192600c020
Revises: 864a241bb009
Create Date: 2023-12-13 10:40:34.442681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50192600c020'
down_revision = '864a241bb009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_html', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_html')

    # ### end Alembic commands ###
