"""empty message

Revision ID: 864a241bb009
Revises: 9c2ddb28d852
Create Date: 2023-12-12 20:41:00.532939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864a241bb009'
down_revision = '9c2ddb28d852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
